{% set name = "bsddb3" %}
{% set version = "6.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70d05ec8dc568f42e70fc919a442e0daadc2a905a1cfb7ca77f549d49d6e7801

build:
  number: 1
  skip: true  # [win or py2k]

requirements:
  build:
    - python {{ python }} 
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - pip
    - libdb
  run:
    - python {{ python }}
    - libdb

test:
  imports:
    - bsddb3

about:
  home: https://www.jcea.es/programacion/pybsddb.htm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python bindings for Oracle Berkeley DB

  description: |
    This module provides a nearly complete wrapping of the Oracle/Sleepycat C API for the Database Environment, 
    Database, Cursor, Log Cursor, Sequence and Transaction objects, 
    and each of these is exposed as a Python type in the bsddb3.db module. 
    The database objects can use various access methods: btree, hash, recno, and queue. 
    Complete support of Berkeley DB distributed transactions. 
    Complete support for Berkeley DB Replication Manager. 
    Complete support for Berkeley DB Base Replication. Support for RPC.
  doc_url: https://www.jcea.es/programacion/pybsddb_doc/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
